version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: health_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1527
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1527@db:5432/health_app
      - POSTGRES_DB=health_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1527
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "sleep 10 &&
             python -c 'from config.database import create_db_and_tables; create_db_and_tables()' &&
             python -c 'from insert_defaults import insert_default_data; insert_default_data()' &&
             uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://206.81.9.180:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
