version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: health_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1527
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d health_app"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1527@db:5432/health_app
      - POSTGRES_DB=health_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1527
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: >
      sh -c "python -c 'from config.database import create_db_and_tables; create_db_and_tables()' &&
             python -c 'from insert_defaults import insert_default_data; insert_default_data()' &&
             uvicorn main:app --host 0.0.0.0 --port 8000"
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://206.81.9.180:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
