version: '3.8'

services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_DB: health_companion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/health_companion
      - POSTGRES_DB=health_companion
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python -c 'from config.database import create_db_and_tables; create_db_and_tables()' &&
             python -c 'from insert_defaults import insert_default_data; insert_default_data()' &&
             uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data: 