services:
  - type: web
    name: my-health-companion-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: health-app-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://my-health-companion.onrender.com

  - type: web
    name: my-health-companion-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://my-health-companion-backend.onrender.com

databases:
  - name: health-app-db
    databaseName: health_app
    user: health_app_user
    plan: free 