services:
  - type: web
    name: my-health-companion-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: health-app-db
          property: connectionString

databases:
  - name: health-app-db
    databaseName: health_app
    user: postgres
    plan: free 